# Series

In [1]:
import pandas as pd

## Create a Series Object from a List
- A `Series` is a single column of ordered homogenous data (data of the same type).
- A `Series` combines the the best features of a list and a dictionary.
- Pandas assigns an identifier to each value. The identifiers make up the **index** of the `Series`.
- If we do not provide a custom index, Pandas defaults to an ascending numeric index.
- The index starts counting from 0.

- A `Series` output includes the data type (`dtype`) of its values.
- `int64` is a 64-bit integer (whole number occupying 64-bits/8 bytes of memory)

- A `Series` can contain duplicates.

## Create a Series Object from a Dictionary
- The `Series` index does not have to be numeric. It can be a variety of data types.
- If we pass a dictionary to the `Series` constructor, Pandas will use the keys as the index labels.
- Pandas will keep track of each element's order (even if the index is non-numeric).

## Intro to Series Methods
- A method is a function attached to an object. It is a command we can issue to the object.
- Invoke a method with the `object.method()` syntax.
- A variable is a name for an existing object. Use `variable.method()` in that case.

In [2]:
adjectives: list[str] = pd.Series(["Smart", "Handsome", "Charming", "Brilliant", "Humble", "Smart"])
adjectives

0        Smart
1     Handsome
2     Charming
3    Brilliant
4       Humble
5        Smart
dtype: str

- The `sum` method adds together the `Series`' values.
- The methods return a `NumPy` scalar value of type `numpy.float64`.
- NumPy is a dependency of Pandas. The `Series` object relies on NumPy's `ndarray` object under the hood.
- JupyterLab prints out the string representation of the NumPy numeric object (`np.float64`)

In [3]:
adjectives.size

6

- Pass a NumPy object into Python's `print` function to see its user-friendly string representation.

In [4]:
adjectives.is_unique

False

- The `product` method multiplies the `Series`' values.
- The `mean` method calculates the average of the `Series`' values.
- The `std` method calculates the standard deviation of the `Series`' values.

In [5]:
adjectives.index

RangeIndex(start=0, stop=6, step=1)

## Intro to Series Attributes
- An **attribute** is a piece of data that lives on an object.
- An **attribute** is a fact, a detail, a characteristic of the object.
- Access an attribute with `object.attribute` syntax.

- The `size` attribute returns a count of the number of values in the `Series`.

- The `is_unique` attribute returns `True` if the `Series` has no duplicate values.

- The `index`return the underlying object that hold the `Series`' index labels.
- You can think of a `Series` object as an collection of other objects.
- Some developers use the word "composition" to define this design. An object is composed of other objects.

- Python's `type` function returns the class of a specified value.
- The class is the blueprint that an object is made from.
- The output can reveal the library that defines the class.
- The `RangeIndex` object/class comes from the Pandas library.

In [6]:
type(adjectives)

pandas.Series

In [7]:
type(adjectives.index)

pandas.RangeIndex

- The `values` attribute returns the object storing the `Series`'s values.

In [8]:
adjectives.values

<StringArray>
['Smart', 'Handsome', 'Charming', 'Brilliant', 'Humble', 'Smart']
Length: 6, dtype: str

In [9]:
type(adjectives.values)

pandas.arrays.StringArray

In [10]:
home_runs:list[int] = pd.Series([3,4,8,2])
home_runs

0    3
1    4
2    8
3    2
dtype: int64

In [11]:
total_home_run : int = home_runs.size
total_home_run

4

In [12]:
average_home_run = home_runs.mean()
average_home_run

np.float64(4.25)

## Parameters and Arguments
- A **parameter** is the name for an expected input to a function/method/class instantiation.
- An **argument** is the concrete value we provide for a parameter during invocation.
- We can pass arguments either sequentially (based on parameter order) or with explicit parameter names written out.

In [13]:
fruits: list[str] = ["Apple", "Orange", "Plum", "Grape", "Blueberry", "Watermelon"]
weekdays: list[str] = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Monday"]

- The first parameter for the `Series` constructor is `data`, which represents the values of the `Series`.
- The constructor will provide fallback/default values to the other parameters.
- Use Shift + Tab to see the `Series` documentation and the default values.
- The `Series` values can contain duplicates.

In [14]:
pd.Series(fruits)
pd.Series(data=fruits)

0         Apple
1        Orange
2          Plum
3         Grape
4     Blueberry
5    Watermelon
dtype: str

- The second parameter for the `Series` constructor is `index`, which holds the index labels.
- Notice that the `Series` index _can_ contain duplicates (although this is not ideal).

In [15]:
pd.Series(fruits, weekdays)
pd.Series(data=fruits, index=weekdays)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: str

- Reversing the order of arguments results in a different `Series`.
- `weekdays` becomes the argument for `data`, and `fruits` becomes the argument for `index`.

In [16]:
pd.Series(weekdays, fruits)

Apple            Monday
Orange          Tuesday
Plum          Wednesday
Grape          Thursday
Blueberry        Friday
Watermelon       Monday
dtype: str

- If using keyword arguments, the order does not matter.
- Python matches the parameter to the argument by its name, not by its order.
- Keyword arguments also provide context on what the parameter represents.

In [17]:
pd.Series(index=weekdays, data=fruits)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: str

- You can mix-and-match positional arguments with keyword arguments.
- Use keyword arguments to skip required arguments.
- The `name` parameter assigns a name to the `Series`.

In [18]:
pd.Series(fruits, index=weekdays)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday          Grape
Friday        Blueberry
Monday       Watermelon
dtype: str

- A `Series` can be empty. Pandas will assume an `object` data type.

In [19]:
pd.Series()

Series([], dtype: object)

## Import Series with the pd.read_csv Function

### The CSV Format
- A comma-separated values (**CSV**) is a plain text file that uses line breaks to separate rows and commas to separate row values.
- The comma-separated values (CSV) format stores one record per row.
- The CSV format separates each row's values with commas.

```
name,strength,magic,speed
Zorblax,9,2,5
Mira,4,9,8
Thud,10,1,2
Eloria,3,10,7
Sorel,2,,4
```

- Pandas ships with many functions for importing different types of files. Their names begin with `read`.
- The `read_csv` function imports a CSV text file.
- The function accepts 30+ parameters. The first one specifies the file name/path.
- The `read_csv` function imports the dataset as a `DataFrame`, a 2-dimensional table.

In [20]:
pd.read_csv("data/csv/pokemon.csv")

              Name              Type
0        Bulbasaur     Grass, Poison
1          Ivysaur     Grass, Poison
2         Venusaur     Grass, Poison
3       Charmander              Fire
4       Charmeleon              Fire
...            ...               ...
1005  Iron Valiant   Fairy, Fighting
1006      Koraidon  Fighting, Dragon
1007      Miraidon  Electric, Dragon
1008  Walking Wake     Water, Dragon
1009   Iron Leaves    Grass, Psychic

[1010 rows x 2 columns]

- The `usecols` parameter accepts a list of the column(s) to import.
- Pandas still imports the dataset as a 1-column `DataFrame`.

In [21]:
pd.read_csv("data/csv/pokemon.csv", usecols=["Name"])

              Name
0        Bulbasaur
1          Ivysaur
2         Venusaur
3       Charmander
4       Charmeleon
...            ...
1005  Iron Valiant
1006      Koraidon
1007      Miraidon
1008  Walking Wake
1009   Iron Leaves

[1010 rows x 1 columns]

- The `squeeze` method converts a 1-column `DataFrame` to a `Series`.
- Pass an argument of `columns` to specify the orientation/direction of the compression (squeeze).
- Let's assign the `DataFrame` to a variable like `pokemon`. This will be our import code at the start of each lesson.

In [22]:
pokemons_name = pd.read_csv("data/csv/pokemon.csv", usecols=["Name"]).squeeze("columns")
pokemons_name

0          Bulbasaur
1            Ivysaur
2           Venusaur
3         Charmander
4         Charmeleon
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 1010, dtype: str

In [23]:
google = pd.read_csv("data/csv/google_stock_prices.csv", usecols=["Price"]).squeeze("columns")
google

0         2.492181
1         2.690134
2         2.717208
3         2.604694
4         2.632761
           ...
5392    333.260010
5393    334.549988
5394    336.010010
5395    338.250000
5396    338.000000
Name: Price, Length: 5397, dtype: float64

In [24]:
# We have a foods.csv CSV file with 3 columns: Item Number, Menu Item, Price
# You can explore the data by clicking into the foods.csv file on the left
# Import the CSV file into a pandas Series object
# The Series should have the standard pandas numeric index
# The Series values should be the string values from the "Menu Item" column
# Assign the Series object to a "foods" variable

foods = pd.read_csv("data/csv/foods.csv", usecols=["Item"]).squeeze()
foods

0         Burger
1        Chalupa
2          Sushi
3      Ice Cream
4        Chalupa
         ...
995        Sushi
996        Sushi
997        Donut
998      Chalupa
999      Chalupa
Name: Item, Length: 1000, dtype: str

## The head and tail Methods
- The `head` method returns a number of rows from the top/beginning of the `Series`.
- The `tail` method returns a number of rows from the bottom/end of the `Series`.

In [25]:
pokemons = pd.read_csv("data/csv/pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("data/csv/google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

In [26]:
pokemons.head(5)
pokemons.head(n=7)

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
5     Charizard
6      Squirtle
Name: Name, dtype: str

In [27]:
google.tail() # default = 5
google.tail(6) 
google.tail(n=8)

5389    328.380005
5390    330.540009
5391    327.929993
5392    333.260010
5393    334.549988
5394    336.010010
5395    338.250000
5396    338.000000
Name: Price, dtype: float64

## Passing Series to Python's Built-In Functions
- Python's functions support Pandas objects as arguments.

In [28]:
pokemons = pd.read_csv("data/csv/pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("data/csv/google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

- The `len` function returns the length of the `Series`.

In [29]:
pokemons.size
len(pokemons)

1010

- The `type` function returns the type of an object.
- `type` can help identify the library that an object is coming from.

In [30]:
type(pokemons)

pandas.Series

- The `list` function converts the `Series` to a list.

In [31]:
list(pokemons.head())

['Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon']

- The `sorted` function converts the `Series` to a sorted list.

In [32]:
sorted(pokemons.head())
sorted(google.head())

[2.492181, 2.604694, 2.632761, 2.690134, 2.717208]

- The `dict` function converts the `Series` to a dictionary.
- The index labels become the keys.

In [33]:
dict(pokemons.head())

{0: 'Bulbasaur', 1: 'Ivysaur', 2: 'Venusaur', 3: 'Charmander', 4: 'Charmeleon'}

- The `max` function returns the largest value in the `Series`.
- The `min` function returns the smallest value in the `Series`.
- The largest value in a string `Series` is the string closest to the end of the alphabet.

In [34]:
max(google)
min(google)

2.483985

In [35]:
max(pokemons)
min(pokemons)

'Abomasnow'

- The `dir` function returns a list of strings with the object's attributes/methods.

In [36]:
dir(pokemons)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

## Check for Inclusion with Python's in Keyword
- The `in` keyword checks if a value exists within an object.
- The `in` keyword will look for a value in the `Series`'s index.
- Use the `index` and `array` attributes to access "nested" objects within the `Series`.
- Combine the `in` keyword with `array` to search within the `Series`'s values.

In [37]:
"car" in "nascar"
2 in (2,3,1)

True

In [38]:
"Bulbasaur" in pokemons.array

True

- Use the `array` attribute to access the underlying object storing the `Series` data.
- The object may vary but it should support Python's `in` keyword to check for inclusion.
- The `values` attribute also works, but the Pandas documentation recommends `array`.

## The sort_values Method
- The `sort_values` method sorts a `Series's` values in order.
- By default, pandas applies an ascending sort (smallest to largest).
- Customize the sort order with the `ascending` parameter.
- The index positions/labels will move with the values.

In [39]:
google.sort_values()
google.sort_values(ascending=False)

5395    338.250000
5396    338.000000
5394    336.010010
5384    335.970001
5385    335.839996
           ...
12        2.522979
10        2.521240
0         2.492181
9         2.489945
11        2.483985
Name: Price, Length: 5397, dtype: float64

In [40]:
pokemons.sort_values(ascending=True) # Default
pokemons.sort_values(ascending=False)

717      Zygarde
633     Zweilous
40         Zubat
569        Zorua
570      Zoroark
         ...
680    Aegislash
616     Accelgor
358        Absol
62          Abra
459    Abomasnow
Name: Name, Length: 1010, dtype: str

In [41]:
pokemons

0          Bulbasaur
1            Ivysaur
2           Venusaur
3         Charmander
4         Charmeleon
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 1010, dtype: str

## The sort_index Method
- The `sort_index` method sorts a `Series` by its index.
- The `sort_index` method also accepts an `ascending` parameter to set the sort order.

In [42]:
pokemons.sort_index()
pokemons.sort_values().sort_index()
pokemons.sort_index(ascending=False)

1009     Iron Leaves
1008    Walking Wake
1007        Miraidon
1006        Koraidon
1005    Iron Valiant
            ...
4         Charmeleon
3         Charmander
2           Venusaur
1            Ivysaur
0          Bulbasaur
Name: Name, Length: 1010, dtype: str

- The `index_col` parameter to `read_csv` sets the index column.

In [43]:
pokemons = pd.read_csv(filepath_or_buffer="data/csv/pokemon.csv", index_col="Name").squeeze("columns")
pokemons

Name
Bulbasaur          Grass, Poison
Ivysaur            Grass, Poison
Venusaur           Grass, Poison
Charmander                  Fire
Charmeleon                  Fire
                      ...
Iron Valiant     Fairy, Fighting
Koraidon        Fighting, Dragon
Miraidon        Electric, Dragon
Walking Wake       Water, Dragon
Iron Leaves       Grass, Psychic
Name: Type, Length: 1010, dtype: str

In [44]:
pokemons.sort_index()

Name
Abomasnow        Grass, Ice
Abra                Psychic
Absol                  Dark
Accelgor                Bug
Aegislash      Steel, Ghost
                  ...
Zoroark                Dark
Zorua                  Dark
Zubat        Poison, Flying
Zweilous       Dark, Dragon
Zygarde      Dragon, Ground
Name: Type, Length: 1010, dtype: str

In [45]:
coffee = pd.read_csv("coffee.csv", index_col="Coffee").squeeze("columns")

flat_white = "Flat White" in coffee.index
cortado = "Cortado" in coffee.index
blackberry_mocha = "Blackberry Mocha" in coffee.index

high_calorie = 221 in coffee.values
super_high_calorie = 400 in coffee.values

coffee.head(5)

Coffee
Americano            202
Black Iced Tea       184
Cappuccino           250
Caramel Macchiato    212
Chai                  93
Name: Calories, dtype: int64

## Extract Series Value by Index Position
- Use the `iloc` accessor to extract a `Series` value by its index position.
- `iloc` is short for "index location".

In [46]:
pokemons = pd.read_csv("data/csv/pokemon.csv", usecols=["Name"]).squeeze("columns")
google = pd.read_csv("data/csv/google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

- Provide square brackets after the accessor. Declare the index position inside the square brackets.

In [47]:
pokemons.iloc[100] # Index Location

'Electrode'

- A nonexistent index will trigger an exception.

In [48]:
# pokemons.iloc[2000] # Error

- Pass a Python list to extract multiple `Series` values by their index positions.

In [49]:
pokemons.iloc[[100,200,300]] # List of value

100    Electrode
200        Unown
300     Delcatty
Name: Name, dtype: str

- The `Series` support's Python's list slicing syntaxes (slices, slices from start, slices to end, etc.) are supported with `Series` objects.

In [60]:
pokemons.iloc[27:36]
pokemons.iloc[0:7]

pokemons.iloc[999:1010]
pokemons.iloc[700:]

700         Hawlucha
701          Dedenne
702          Carbink
703            Goomy
704          Sliggoo
            ...
1005    Iron Valiant
1006        Koraidon
1007        Miraidon
1008    Walking Wake
1009     Iron Leaves
Name: Name, Length: 310, dtype: str

- Pandas also supports negative values and negative slices.
- -1 pulls the last value, -10 pulls the value 10 from the end.
- The second number is exclusive. `-10:-5` will pull the value 10 from the end up until (but not including) 5 from the end.

In [63]:
pokemons.iloc[-10:-5]
pokemons.iloc[-10:]
pokemons.iloc[-len(pokemons):-len(pokemons) + 10]

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
5     Charizard
6      Squirtle
7     Wartortle
8     Blastoise
9      Caterpie
Name: Name, dtype: str

- The `iat` accessor accepts only a single index value.
- The `iat` accessor does _not_ support lists or slices.
- The advantage of the restriction is that access is generally faster than `iloc`.
- Pandas does not need to figure out the argument type.

In [ ]:
# Index at
pokemons.iat[1000]

'Wo-Chien'

## Extract Series Value by Index Label
- Use the `loc` accessor to extract a `Series` value by its index label.
- Pass a list to extract multiple values by index label.
- If one index label/position in the list does not exist, Pandas will raise an error.

In [69]:
pokemons = pd.read_csv("data/csv/pokemon.csv", index_col=["Name"]).squeeze("columns").sort_index()
google = pd.read_csv("data/csv/google_stock_prices.csv", usecols=["Price"]).squeeze("columns")

pokemons.head()

Name
Abomasnow      Grass, Ice
Abra              Psychic
Absol                Dark
Accelgor              Bug
Aegislash    Steel, Ghost
Name: Type, dtype: str

In [74]:
pokemons.loc["Bulbasaur"]
pokemons.loc["Abra"]
pokemons.loc["Pikachu"]

'Electric'

In [ ]:
pokemons.loc[["Pikachu", "Charizard", "Jolteon"]]
pokemons.loc[[ "Charizard","Pikachu", "Jolteon"]]

Name
Pikachu          Electric
Charizard    Fire, Flying
Jolteon          Electric
Name: Type, dtype: str

- The `at` accessor is complementary to `loc`, much like `iat` is complementary to `iloc`.
- It only supports a single index label. It does not support slices or lists. The constraint enables it to be faster for single-index targets.

## The get Method on a Series
- The `get` method extracts a `Series` value by index label. It is an alternative option to square brackets.

- The `get` method accepts a list of multiple index labels.

- Square brackets raise an exception if the key does not exist.
- The `get` method's second argument sets the fallback value to return if the label/position does not exist.
- The default value for the default is `None`, which has no printed representation.

- We can also a pass list to extract multiple elements.

## Overwrite a Series Value
- Use the `loc`/`iloc` accessor to target an index label/position, then use an equal sign to provide a new value.

- The `Series` maintains a numeric order of values even if the index is not numeric.

## Copy-on-Write and the copy Method
- In earlier versions of Pandas (`< 3.0`), targeting data could return a view.
- A view was a window/alternate perspective into the *same* underlying data.
- Changes to the view would mutate the original object that the view was referencing.
- Pandas 3.0 follows a **Copy-on-Write** principle.
    1. Any object derived from another behaves as an independent copy.
    2. When code mutates the underlying data, Pandas will create a copy to avoid unexpected side effects.
- A **copy** is a duplicate/clone of an object.

- Let's assign the imported `DataFrame` to a `pokemon_df` variable.
- We'll then use it as the basis of creating a `Series` assigned to `pokemon_series`.
- `pokemon_series` share the same data under the hood as the `DataFrame`.
- Pandas has no reason to copy the data yet (and use more memory).

- Let's use the `iloc` accesor to update the `Series` at index position 0.
- Pandas sees the mutation of the underlying data. It creates a copy of the data for the `Series`.

- The original `pokemon_df` `DataFrame` is **not** mutated.
- The Copy-on-Write principle in Pandas 3 force a copy of the `Series` data when we mutate it (`iloc`).
- `pokemon_series` _was_ relying on shared data before `iloc` but now has its own copy of the data.

- In previous version of Pandas, we would see different behavior.
- Mutating the `Series` would mutate the `DataFrame` as well.
- In previous versions, invoke the `copy` method explicitly to force a copy of the `Series` data.

## Math Methods on Series

- The `count` method returns the number of present values in the `Series`.
- The `count` method excludes missing values.
- The `size` attribute includes missing values (the `len` function is another option).

- The `sum` method adds together the `Series`'s values.

- The `product` method multiplies together the `Series`'s values.

- The `mean` method calculates the average of the `Series`'s values.

- The `std` method calculates the standard deviation of the `Series`'s values.

- The `max` method returns the largest value in the `Series`.
- The `min` method returns the smallest value in the `Series`.

- The `idxmin` and `idxmax` methods return the index label where the smallest/largest value occurs.

- We can confirm the value is correct by extracting it by the index.


- The `median` method returns the median of the `Series` (the value in the middle).

- The `mode` method returns the mode of the `Series` (the most frequent value).

- The `describe` method returns a summary with various mathematical calculations.
- The output includes the quartiles. 25% of the values are less than or equal to 13.295.

- The `quantile` method returns any percentile.
- The argument should be a decimal between 0 and 1.

- The `quantile` method accepts a list of multiple percentiles.
- Pandas will return a `Series`. The index labels will be the percentiles.

## Broadcasting
- **Broadcasting** is the process of applying a consistent mathematical operation to every `Series` value.
- Use a mathematical operator with a `Series` to apply the mathematical operation to every value.
- There are also methods to accomplish the same results (`add`, `sub`, `mul`, `div`, etc.)

- Wrap the operation in parentheses to invoke a method upon the resulting object.
- Alternatively, assign the result to a variable.

- Use `-` for subtraction, `*` for multiplication, `/` for division, and `//` for floor division.
- We can reverse the operands around the operator if the operation is logically the same.

## Pandas Aligns by Index Label
- We can perform mathematical operations between multiple `Series`.
- Pandas will align values by index labels, not by position.
- The resulting index will be the union (combination) of all index labels from the two `Series`.
- `NaN` is Pandas' designation for a missing value.
- Any label present in one `Series` but missing in the other produces `NaN` in the result. Pandas cannot add "unknown" to a valid numeric value.

- Let's find the total business revenue per day/index label.
- The `Tue` and `Wed` labels are found in both `Series.`
- The `Mon` label is only found in `revenue_ny`.
- The `Thu` label is only found in `revenue_la`.

- The `add` method supports a `fill_value` parameter to provide a fallback value for missing labels.
- Pandas will assign the present label value with the `fill_value`.

## The value_counts Method
- The `value_counts` method returns the number of times that each distinct value occurs in the `Series`.

- Pandas returns the values in descending order (most frequent first).

- The `ascending` parameter customizes the sort order. An ascending sort places the smallest values first.

- The `normalize` parameter returns the relative frequencies/percentages of the values instead of the counts.
- Multiply by 100% to get the percentage.

## The apply Method
- The `apply` method invokes a function on every `Series` value.
- The method accepts the _uninvoked_ function.

- The `apply` method supports custom functions as well.
- A pandas method for an operation will usually be faster.
- But, if you don't know the right pandas method and can write the logic in Python, `apply` is a great workaround.

## The map Method
- The `map` method associates or connects each `Series` value to another value.
- We can pass the method a dictionary or a `Series`. Both types connect keys to values.
- The `map` method uses our argument to connect or bridge together the values.

- Let's define a dictionary mapping types to attack powers.

- Pandas will map/connect each `Series` index label to the complementary dictionary value by matching the key.

- The `map` method also accepts another `Series` as an argument.
- Pandas will map the index labels from `pokemon` to the index labels in `attack_powers_series`.
- It will match the corresponding attack power value for each Pokemon.